name: Merge Open PRs
on:
  schedule:
    - cron: '0 15 * * *' # KST 00:00
    - cron: '50 16 * * *' # KST 01:00

jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo current time
        run: echo "Workflow triggered at $(date)"

  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List open pull requests using API
      id: list-prs
      run: |
        PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
        
        PR_LIST=$(echo "$PRS" | jq -r '.[].number' | paste -sd ',' -)
    
        echo "PR_LIST=$PR_LIST" >> $GITHUB_ENV

    - name: Merge eligible PRs
      if: ${{ env.PR_LIST }}
      run: |
        echo "Merging open pull requests..."
        PR_LIST=${{ env.PR_LIST }}

        IFS=',' read -r -a PR_ARRAY <<< "$PR_LIST"

        for PR_NUMBER in "${PR_ARRAY[@]}"; do
          echo "Merging PR #$PR_NUMBER..."
          if gh pr merge $PR_NUMBER --repo $GITHUB_REPOSITORY --merge; then
            echo "Successfully merged PR #$PR_NUMBER."
          else
            echo "Failed to merge PR #$PR_NUMBER. Continuing..."
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: No PRs to merge
      if: ${{ !env.PR_LIST }}
      run: echo "No open pull requests eligible for merge."
